### ISSUE TITLE
How to integration other MQ project

### ISSUE THREAD

**Issue by yifanzzz** [mminella/LearningSpringBatch#1]
spring batch must integration with JMS or rabbitmq?  if i want to integrator with kafaka or rocketmq or other project or procotol, how to support?

**Comment by mminella** [comment]
Spring Batch integrates with JMS and AMQP natively and we just released Kafka based reader/writer today: https://spring.io/blog/2019/05/13/spring-batch-4-2-0-m2-available-now

Going forward, please post questions like this in StackOverflow and tag it as `spring-batch`.  The entire Spring Batch team monitors those and will be sure to respond ASAP.

Thanks!
